function Grafica(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
 
%  Auto-generated by MATLAB on 14-Feb-2020 06:40:23
 
% Create figure
figure1 = figure;
 
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
 
% Create plot
plot(X1,Y1);
 
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XAxisLocation','origin','XColor',[0 0 0],'XGrid','on',...
'XMinorGrid','on','YAxisLocation','origin','YColor',[0 0 0],'YGrid','on',...
'YMinorGrid','on','ZColor',[0 0 0]);
