function Grafica3D(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data
 
%  Auto-generated by MATLAB on 14-Feb-2020 08:50:20
 
% Create figure
figure1 = figure;
 
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
 
% Create plot3
plot3(X1,Y1,Z1,'LineWidth',2,'Color',[1 0 0]);
 
view(axes1,[-37.5 30]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XAxisLocation','origin','YAxisLocation','origin');
